services:
  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/:/etc/nginx/templates/"
      - "${VOLUME_WORDPRESS_PATH:-../../../}:/var/www/html:rw,cached"
      - "${VOLUME_LOCAL_PACKAGES_PATH}:/var/www/local-packages:rw,cached"
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN=${LOCAL_DOMAIN}"
      - "MULTISITE=${MULTISITE:-0}"
    depends_on:
      - wordpress
    restart: always
    logging:
      driver: ${DOCKER_LOGGING_DRIVER_NGINX:-none}

  mysql:
    image: mariadb:10.7
    container_name: ${APP_NAME}-mysql
    command: --defaults-extra-file=/etc/mysql/conf.d/mariadb.cnf --lower_case_table_names=2
    volumes:
      - "${VOLUME_WORDPRESS_PATH:-../../../}data/db:/var/lib/mysql:delegated,rw"
      - ./config/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - "3306:3306"
    logging:
      driver: ${DOCKER_LOGGING_DRIVER_MYSQL:-none}

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-wordpress
    volumes:
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./config/fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - "${VOLUME_WORDPRESS_PATH:-../../../}:/var/www/html:rw,cached"
      - "${VOLUME_LOCAL_PACKAGES_PATH}:/var/www/local-packages:rw,cached"
    depends_on:
      - mysql
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: ${DOCKER_LOGGING_DRIVER_WP:-none}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "8082:80"
    links:
      - mysql:mysql
    logging:
      driver: ${DOCKER_LOGGING_DRIVER_PHPMYADMIN:-none}

  mailhog:
    image: mailhog/mailhog
    container_name: ${APP_NAME}-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    logging:
      driver: ${DOCKER_LOGGING_DRIVER_MAILHOG:-none}

  composer:
    image: composer
    container_name: ${APP_NAME}-composer
    working_dir: /var/www/html
    restart: "no"
    environment:
      - "COMPOSER_IGNORE_PLATFORM_REQS=1"
    volumes:
      - "${VOLUME_WORDPRESS_PATH:-../../../}:/var/www/html:rw,cached"
      - "${VOLUME_LOCAL_PACKAGES_PATH}:/var/www/local-packages:rw,cached"
    logging:
      driver: ${DOCKER_LOGGING_DRIVER_COMPOSER:-none}
