[xdebug]
xdebug.mode = debug,profile
; Switch from "trigger" to "yes" to start Xdebug automatically on page load, making it easier to debug AJAX requests (reload the WP container after changing)
; xdebug.start_with_request = trigger 
xdebug.start_with_request = yes 
xdebug.output_dir = /tmp
xdebug.client_port = 9003
xdebug.client_host = host.docker.internal
xdebug.log = /tmp/xdebug.log
xdebug.connect_timeout_ms = 600
